SELECT
STATES.STATENAME
,AREACODE.AREAID
,sum(FACTCOFFEE.ACTSALES) "Area Code Sales"
,round(AvgSales.SalesPerCode,2) "State Average"
,round(100*sum(FACTCOFFEE.ACTSALES)/AvgSales.SalesPerCode,2) "%OverStateAvg"

FROM
FACTCOFFEE
inner join AREACODE on FACTCOFFEE.AREAID = AREACODE.AREAID
inner join STATES on AREACODE.STATEID = STATES.STATEID
inner join 
(
SELECT
STATES.STATENAME
,sum(FACTCOFFEE.ACTSALES)/count(distinct FACTCOFFEE.AREAID) SalesPerCode
FROM
FACTCOFFEE
inner join AREACODE on FACTCOFFEE.AREAID = AREACODE.AREAID
inner join STATES on AREACODE.STATEID = STATES.STATEID
WHERE
EXTRACT(YEAR from FACTCOFFEE.FACTDATE) = 2013
GROUP BY
STATES.STATENAME
) AvgSales on AvgSales.STATENAME = STATES.STATENAME

WHERE
EXTRACT(YEAR from FACTCOFFEE.FACTDATE) = 2013

GROUP BY
STATES.STATENAME
,AREACODE.AREAID
,AvgSales.SalesPerCode

HAVING
sum(FACTCOFFEE.ACTSALES)/AvgSales.SalesPerCode >= 1.1

Order by
sum(FACTCOFFEE.ACTSALES)/AvgSales.SalesPerCode desc
;
